name: Core Engine CI Tests

# Yeh workflow tab chalega jab koi 'main'  branch par push ya pull request karega
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: [self-hosted, linux, GPU] # Cause we need GPU for NVCC 

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure CMake
      # Project ko build folder mein configure karega 
      run: cmake -B build -DCMAKE_BUILD_TYPE=Debug -S .

    - name: Build Project
      # Code ko compile karega 
      run: cmake --build build

    - name: List Discovered Tests
      run: cd build && ctest --show-only

    - name: Run Unit Tests
      # Agar tumne CTest use kiya hai, toh yeh saare tests run karega
      run: cd build && ctest --output-on-failure --verbose -j2
    
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: build/Testing/
        retention-days: 7
